--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MintoD3v/TrashCan
build-by-default: true
branches:
- main
projects:
  TrashCan:
    path: ""
    libs:
    - src: Muqsit/InvMenu/InvMenu
      version: ^4.6.1
      branch: "pm5"
...
