--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MintoD/TrashCan
build-by-default: true
branches:
- main
projects:
  TrashCan:
    path: ""
    libs:
    - src: Muqsit/InvMenu/InvMenu
      version: ^4.3.4
      branch: 4.0
...
