name: TrashCan
author: [MintoD, thebigcrafter]
version: 2.0.0
api: 5.0.0
main: MintoD\TrashCan\TrashCan

commands:
  trashcan:
    description: Open trash can
    permission: trashcan.cmd

permissions:
  trashcan.cmd:
    description: Allows the player to open the trash can
    default: true
